GAME_FIELD_WIDTH = 800
FIGURE_STORE_WIDTH = 300
SCREEN_WIDTH = GAME_FIELD_WIDTH + FIGURE_STORE_WIDTH
GAME_FIELD_HEIGHT = 800
SCREEN_HEIGHT = GAME_FIELD_HEIGHT
CELL_SIDE = 6
CELLS_IN_ROW = int(GAME_FIELD_WIDTH / CELL_SIDE)
CELLS_IN_COLUMN = int(GAME_FIELD_HEIGHT / CELL_SIDE)